In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [61]:
df = pd.read_csv("/content/drive/MyDrive/football/players_20.csv")
df.head()

sofifa_id                                         player_url  ...   rcb    rb
0     158023  https://sofifa.com/player/158023/lionel-messi/...  ...  52+2  63+2
1      20801  https://sofifa.com/player/20801/c-ronaldo-dos-...  ...  53+3  61+3
2     190871  https://sofifa.com/player/190871/neymar-da-sil...  ...  46+3  61+3
3     200389  https://sofifa.com/player/200389/jan-oblak/20/...  ...   NaN   NaN
4     183277  https://sofifa.com/player/183277/eden-hazard/2...  ...  49+3  61+3

[5 rows x 104 columns]

In [62]:
df['gk_diving']=df.gk_diving.fillna(df.gk_diving.mean())
df['gk_handling']=df.gk_handling.fillna(df.gk_handling.mean())
df['gk_kicking']=df.gk_kicking.fillna(df.gk_kicking.mean())
df['gk_reflexes']=df.gk_reflexes.fillna(df.gk_reflexes.mean())
df['gk_speed']=df.gk_speed.fillna(df.gk_speed.mean())
df['gk_positioning']=df.gk_positioning.fillna(df.gk_positioning.mean())
df['pace']=df.pace.fillna(df.pace.mean())
df['shooting']=df.shooting.fillna(df.shooting.mean())
df['passing']=df.passing.fillna(df.passing.mean())
df['defending']=df.defending.fillna(df.defending.mean())
df['physic']=df.physic.fillna(df.physic.mean())
df['dribbling']=df.dribbling.fillna(df.dribbling.mean())

df['nation_position']=df.nation_position.fillna(df.nation_position.value_counts().index[0])
df['team_position']=df.team_position.fillna(df.team_position.value_counts().index[0])

In [67]:
columns = ['sofifa_id','short_name','pace', 'defending', 'passing', 'shooting', 'dribbling', 'gk_handling', 'gk_kicking', 'gk_reflexes', 'gk_speed','gk_diving' ,'gk_positioning', 'overall']
df = df[columns]
df.head()
df.isnull().values.any()

False

In [68]:
df = df.to_numpy()

In [69]:
df.shape

(18278, 14)

In [70]:
import random
np.random.shuffle(df)
df


array([[229677, 'F. Bambock', 62.0, ..., 65.42239685658153,
        63.37475442043222, 67],
       [250911, 'B. Santelli', 79.0, ..., 65.42239685658153,
        63.37475442043222, 63],
       [193645, 'D. Gavazzi', 72.0, ..., 65.42239685658153,
        63.37475442043222, 68],
       ...,
       [233961, 'S. Al Najai', 65.0, ..., 65.42239685658153,
        63.37475442043222, 60],
       [226757, 'M. Escudero', 55.0, ..., 65.42239685658153,
        63.37475442043222, 67],
       [241192, 'D. Balanyuk', 71.0, ..., 65.42239685658153,
        63.37475442043222, 60]], dtype=object)

In [71]:
df.shape

(18278, 14)

In [72]:
split = (70 , 30) 

In [73]:
train_dataset_split = int(df.shape[0]* split[0]/100)
train_dataset_split

12794

In [74]:
train_dataset = df[:train_dataset_split]

In [75]:
test_dataset = df[train_dataset_split:]

In [76]:
train_dataset[:3]

array([[229677, 'F. Bambock', 62.0, 66.0, 56.0, 49.0, 60.0,
        63.146365422396855, 61.832514734774065, 66.39047151277013,
        37.79862475442043, 65.42239685658153, 63.37475442043222, 67],
       [250911, 'B. Santelli', 79.0, 24.0, 53.0, 58.0, 66.0,
        63.146365422396855, 61.832514734774065, 66.39047151277013,
        37.79862475442043, 65.42239685658153, 63.37475442043222, 63],
       [193645, 'D. Gavazzi', 72.0, 59.0, 66.0, 63.0, 68.0,
        63.146365422396855, 61.832514734774065, 66.39047151277013,
        37.79862475442043, 65.42239685658153, 63.37475442043222, 68]],
      dtype=object)

In [86]:
X_train = train_dataset[:,2:-1]
X_train[:3]

array([[62.0, 66.0, 56.0, 49.0, 60.0, 63.146365422396855,
        61.832514734774065, 66.39047151277013, 37.79862475442043,
        65.42239685658153, 63.37475442043222],
       [79.0, 24.0, 53.0, 58.0, 66.0, 63.146365422396855,
        61.832514734774065, 66.39047151277013, 37.79862475442043,
        65.42239685658153, 63.37475442043222],
       [72.0, 59.0, 66.0, 63.0, 68.0, 63.146365422396855,
        61.832514734774065, 66.39047151277013, 37.79862475442043,
        65.42239685658153, 63.37475442043222]], dtype=object)

In [79]:
y_train = train_dataset[:,-1].reshape(-1, 1)
y_train

array([[67],
       [63],
       [68],
       ...,
       [58],
       [64],
       [67]], dtype=object)

In [87]:
X_test = test_dataset[:,2:-1]
X_test[0:3]

array([[61.0, 77.0, 82.0, 70.0, 77.0, 63.146365422396855,
        61.832514734774065, 66.39047151277013, 37.79862475442043,
        65.42239685658153, 63.37475442043222],
       [73.0, 68.0, 62.0, 56.0, 65.0, 63.146365422396855,
        61.832514734774065, 66.39047151277013, 37.79862475442043,
        65.42239685658153, 63.37475442043222],
       [74.0, 60.0, 62.0, 60.0, 64.0, 63.146365422396855,
        61.832514734774065, 66.39047151277013, 37.79862475442043,
        65.42239685658153, 63.37475442043222]], dtype=object)

In [88]:
y_test = test_dataset[:,-1].reshape(-1, 1)
y_test

array([[81],
       [70],
       [66],
       ...,
       [60],
       [67],
       [60]], dtype=object)

In [84]:
import xgboost as xgb

In [89]:
xgb_model = xgb.XGBRegressor(objective="reg:squarederror")
xgb_model.fit(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:squarederror',
             random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             seed=None, silent=None, subsample=1, verbosity=1)

In [90]:
predict = xgb_model.predict(X_test)
predict

array([81.06747 , 69.472855, 65.36394 , ..., 61.713135, 66.70131 ,
       60.436165], dtype=float32)

In [91]:
xgb_model.score(X_train,y_train) * 100

95.40184071734744

In [92]:
xgb_model.score(X_test,y_test) *100

95.30200123261956

In [94]:
test_dataset[:,[1,-1]].shape

(5484, 2)

In [97]:
predict1 = predict.reshape(-1,1)

In [103]:
prediction_df = np.concatenate((test_dataset[:,[1,-1]],predict1), axis = 1)
prediction_df

array([['J. Milner', 81, 81.06746673583984],
       ['C. Fuentes', 70, 69.47285461425781],
       ['M. Benning', 66, 65.36393737792969],
       ...,
       ['S. Al Najai', 60, 61.713134765625],
       ['M. Escudero', 67, 66.70130920410156],
       ['D. Balanyuk', 60, 60.43616485595703]], dtype=object)

In [115]:
rating_df = pd.DataFrame(data=prediction_df,columns=['name', 'rating', 'prediction'])
rating_df['difference'] = abs(rating_df['rating'] - rating_df['prediction'])
rating_df.sort_values(by='difference')

name rating prediction   difference
5174  S. Abdulhamid     61    60.9999  0.000102997
1986         A. Dia     55    54.9998  0.000228882
1410    P. Ulvestad     63    63.0003   0.00030899
1364      L. Contin     60     60.001  0.000953674
1667   G. Gazzaniga     64    64.0011   0.00110626
...             ...    ...        ...          ...
4834        A. Zeka     57     63.003      6.00296
2499   M. Mandžukić     84    77.9822       6.0178
5132      M. Marega     80    73.9817      6.01826
4670     S. Darbion     65    71.0397      6.03974
3339      M. Diagne     78    69.7211      8.27888

[5484 rows x 4 columns]

In [109]:
rating_df[rating_df['name'] == 'J. Oblak']

name rating prediction
5118  J. Oblak     91     85.761